# Multi-Container Monitoring System
# Consolidated Docker Compose with enhanced logging and monitoring

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  web1:
    image: nginx:alpine
    container_name: web1
    logging: *default-logging
    volumes:
      - web1-content:/usr/share/nginx/html
    ports:
      - "8081:80"
    environment:
      - CONTAINER_ID=web1
      - TZ=Asia/Colombo

  web2:
    image: nginx:alpine
    container_name: web2
    logging: *default-logging
    volumes:
      - web2-content:/usr/share/nginx/html
    ports:
      - "8082:80"
    environment:
      - CONTAINER_ID=web2
      - TZ=Asia/Colombo

  db:
    image: postgres:16-alpine
    container_name: db
    logging: *default-logging
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: monitoruser
      POSTGRES_PASSWORD: monitorpass
      TZ: Asia/Colombo
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  watchdog:
    build: ./watchdog
    container_name: watchdog
    logging: *default-logging
    environment:
      - TARGET_TIMEZONE=Asia/Colombo
      - TZ=Asia/Colombo
      - WEB_TARGETS=web1:80,web2:80
      - EXPECT_TEXT=Multi-Container Monitoring OK
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=monitoring
      - DB_USER=monitoruser
      - DB_PASSWORD=monitorpass
      - CHECK_INTERVAL_SEC=60
      - MAX_ALLOWED_DRIFT_SEC=5
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - SMTP_FROM=alerts@monitoring.local
      - SMTP_TO=support@monitoring.local
      - LOG_LEVEL=INFO
    volumes:
      - web1-content:/sites/web1
      - web2-content:/sites/web2
      - monitoring-logs:/var/log/monitoring
    depends_on:
      - db
      - web1
      - web2

  log-viewer:
    build: ./logging
    container_name: log-viewer
    logging: *default-logging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - monitoring-logs:/var/log/monitoring
    ports:
      - "8090:80"
    depends_on:
      - db
      - watchdog
    environment:
      - TZ=Asia/Colombo

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    logging: *default-logging
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - TZ=Asia/Colombo

volumes:
  db-data:
  web1-content:
  web2-content:
  monitoring-logs:
