apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
