apiVersion: apps/v1
kind: Deployment
metadata:
  name: web2
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web2
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
        - name: web2
          image: nginx:alpine
          ports:
            - containerPort: 80
          env:
            - name: CONTAINER_ID
              value: "web2"  
          envFrom:
            - configMapRef:
                name: monitoring-config
          volumeMounts:
            - name: web2-content
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web2-content
          persistentVolumeClaim:
            claimName: web2-content-pvc
